spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aak_workshops
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
